name: kapstr
description: "Application de gestion d'évènements"

publish_to: 'none'


version: 2.5.5+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  # Widgets et UI (User Interface)

  
  persistent_bottom_nav_bar_v2: ^5.2.3
  percent_indicator: ^4.2.0
  reorderable_grid_view: ^2.2.6
  pinput: ^5.0.0
  flutter_colorpicker: ^1.0.3
  flutter_font_picker: ^1.1.2
  loading_skeleton_niu: ^0.0.1
  flutter_email_sender: ^6.0.3
  flutter_speed_dial: ^7.0.0
  smooth_page_indicator: ^1.1.0
  add_2_calendar: ^3.0.1
  file_picker: ^8.1.2
  video_player: ^2.8.2
  flutter_libphonenumber: ^2.2.1
  chewie: ^1.7.4
  flutter_pdfview: ^1.3.2
  vimeo_player_flutter: ^0.1.0
  youtube_player_flutter: ^9.1.1
  flutter_image_compress: ^2.1.0
  flex_color_picker: ^3.3.1
  vibration: ^3.1.2
  flutter_native_splash: ^2.4.0
  palette_generator: ^0.3.3+3
  shared_preferences: ^2.2.2
  http: ^1.2.1
  confetti: ^0.8.0
  in_app_purchase: ^3.2.0
  intl_phone_number_input: ^0.7.4
  permission_handler: ^11.3.1
  dio: ^5.7.0

  # Authentification
  firebase_auth: ^5.3.1
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.2
  image: ^4.2.0

  # Base de données et stockage
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  path_provider: ^2.1.1
  cloud_functions: ^5.1.3
  flutter_local_notifications: ^18.0.1

  # Traitement des images et médias
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  image_cropper: ^9.0.0
  cached_network_image: ^3.2.3

  # Communication et services
  mailer: ^6.0.1

  # Cartographie et géolocalisation
  google_maps_flutter: ^2.5.3
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.7
  flutter_sound: ^9.6.0
  rxdart: ^0.27.7

  # Fonctionnalités spécifiques au système
  device_info_plus: ^11.2.2
  ios_utsname_ext: ^2.2.0
  flutter_file_dialog: ^3.0.2
  flutter_cache_manager: ^3.3.2

  # Utilitaires et outils divers
  numberpicker: ^2.1.1
  url_launcher: ^6.1.7
  intl: ^0.19.0
  fl_country_code_picker: ^0.1.7+1
  google_fonts: ^5.1.0
  provider: ^6.0.5
  share_plus: ^10.0.2
  flutter_localization: ^0.3.1

  # Icônes
  material_symbols_icons: ^4.2668.0
  cupertino_icons: ^1.0.2

  # Tests
  flutter_test:
    sdk: flutter
  firebase_app_check: ^0.3.1+3
  firebase_messaging: ^15.1.3
  haptic_feedback: ^0.5.1+1
  uuid: ^4.4.0
  in_app_purchase_storekit: ^0.3.18+1
  in_app_purchase_android: ^0.4.0
  animated_widgets: ^1.1.0
  flutter_localizations:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: true
  image: assets/icons/app/splash.png
  color: "#FFFFFF"

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_app_name:
  name: "Kapstr"

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/app/ic_launcher.png"
  image_path_android: "assets/icons/app/ic_launcher.png"
  adaptive_icon_background: "assets/icons/app/background.png"
  adaptive_icon_foreground: "assets/icons/app/foreground.png"


flutter:

  uses-material-design: true

  #ASSETS

  assets:
    - assets/
    - assets/seating.svg
    - assets/logos/
    - assets/icons/
    - assets/icons/tabbar/
    - assets/icons/app/
    - assets/images/

  #FONTS

  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/avenir_light.ttf
          weight: 200
        - asset: fonts/avenir_regular.otf
          weight: 400
        - asset: fonts/avenir_medium.ttf
          weight: 500
        - asset: fonts/avenir_semibold.otf
          weight: 600
        - asset: fonts/avenir_black.ttf
          weight: 700
    - family: Impact
      fonts:
        - asset: fonts/impact.ttf
    - family: SnellRoundhand
      fonts:
        - asset: fonts/SnellBT-Regular.otf
          weight: 400
        - asset: fonts/SnellBT-Bold.otf
          weight: 700
